#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ -z "$branch" ]]; then
    branch="UNSPECIFIED"
fi

latest="$(git log -n 1 --pretty='%H')"
if [[ -z "$latest" ]]; then
    latest="UNSPECIFIED"
fi

commit_time="$(git log --pretty='%ci' -n 1)"
if [[ -z "$commit_time" ]]; then
    commit_time="UNSPECIFIED"
fi

porcelain="$(git status --porcelain 2>/dev/null| wc -l | tr -d [:blank:])"

file="#ifndef _VERSION_H
#define _VERSION_H

// Automatically generated by version.h

#include <string>

std::string Hadron_PDFs_compilation(){
    std::string info=\"Hadron_PDFs COMPILATION INFORMATION\n\";
    info+=\"========================================================================================\n\";
    info+=\"git branch:         ${branch}\n\";
    info+=\"git commit:         ${latest}\n\";
    info+=\"git commit time:    ${commit_time}\n\";
    info+=\"compilation time:   $(date "+%Y-%m-%dT%H:%M")\n\";
"

if [[ ! -z "${porcelain}" ]]; then
    file+="    info+=\"WARNING:            COMPILED AGAINST AN UNCLEAN REPO\n\";
    info+=\"dirty files:        ${porcelain}\n\";
";
fi

file+="    info+=\"========================================================================================\";
    
    return info;
}

#endif // _VERSION_H"

echo "$file"
